"""Adding venue Looking for Talent & Seeking Info

Revision ID: 6b69c803549b
Revises: 8d00ec30e8d4
Create Date: 2022-08-06 15:11:41.973246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b69c803549b'
down_revision = '8d00ec30e8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeing_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeing_desc')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
