"""2) Adding music genres table

Revision ID: 840388fbf33e
Revises: 09a0852bc158
Create Date: 2022-08-06 14:04:16.174995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840388fbf33e'
down_revision = '09a0852bc158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genre_table = op.create_table('Genre',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(genre_table,
    [
        { 'id':0, 'name':'Other' },
        { 'id':1, 'name':'Alternative' },
        { 'id':2, 'name':'Blues' },
        { 'id':3, 'name':'Classical' },
        { 'id':4, 'name':'Country' },
        { 'id':5, 'name':'Electronic' },
        { 'id':6, 'name':'Folk' },
        { 'id':7, 'name':'Funk' },
        { 'id':8, 'name':'Hip-Hop' },
        { 'id':9, 'name':'Heavy Metal' },
        { 'id':10, 'name':'Instrumental' },
        { 'id':11, 'name':'Jazz' },
        { 'id':12, 'name':'Musical Theatre' },
        { 'id':13, 'name':'Pop' },
        { 'id':14, 'name':'Punk' },
        { 'id':15, 'name':'R&B' },
        { 'id':16, 'name':'Reggae' },
        { 'id':17, 'name':'Rock n Roll' },
        { 'id':18, 'name':'Soul' },
    ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genre')
    # ### end Alembic commands ###
