"""3) Adding venue genres association

Revision ID: 8d00ec30e8d4
Revises: 840388fbf33e
Create Date: 2022-08-06 14:05:26.160326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d00ec30e8d4'
down_revision = '840388fbf33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genre_venue_table = op.create_table('genre_venue_assoc',
        sa.Column('venue_id', sa.Integer(), nullable=False),
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
        sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
        sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.bulk_insert(genre_venue_table,
    [
        { 'venue_id': 1, 'genre_id': 11 },
        { 'venue_id': 1, 'genre_id': 16},
        { 'venue_id': 1, 'genre_id': 19},
        { 'venue_id': 1, 'genre_id': 3},
        { 'venue_id': 1, 'genre_id': 6},

        { 'venue_id': 2, 'genre_id': 3},
        { 'venue_id': 2, 'genre_id': 15},
        { 'venue_id': 2, 'genre_id': 8},

        { 'venue_id': 3, 'genre_id': 17},
        { 'venue_id': 3, 'genre_id': 11},
        { 'venue_id': 3, 'genre_id': 3},
        { 'venue_id': 3, 'genre_id': 6},

        { 'venue_id': 4, 'genre_id': 11},
        { 'venue_id': 4, 'genre_id': 5},
        { 'venue_id': 4, 'genre_id': 16},

        { 'venue_id': 5, 'genre_id': 1},
        { 'venue_id': 5, 'genre_id': 5}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_venue_assoc')
    # ### end Alembic commands ###
