"""4) Adding show to the model - with show DateTime

Revision ID: a920576e1016
Revises: 6b69c803549b
Create Date: 2022-08-06 16:22:37.721370

"""
from alembic import op
import sqlalchemy as sa
from common_handles import db

# revision identifiers, used by Alembic.
revision = 'a920576e1016'
down_revision = '8d00ec30e8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    show_table = op.create_table('Show',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('venue_id', sa.Integer(), nullable=True),
        sa.Column('artist_id', sa.Integer(), nullable=True),
        sa.Column('show_start_time', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
        sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(show_table,
    [
        {'id':0, 'venue_id': 1, 'artist_id': 4, 'show_start_time': '2019-05-21T21:30:00.000Z' },
        {'id':1, 'venue_id': 3, 'artist_id': 5, 'show_start_time': '2019-06-15T23:00:00.000Z' },
        {'id':2, 'venue_id': 3, 'artist_id': 7, 'show_start_time': '2035-04-01T20:00:00.000Z' },
        {'id':3, 'venue_id': 3, 'artist_id': 7, 'show_start_time': '2035-04-08T20:00:00.000Z' },
        {'id':4, 'venue_id': 3, 'artist_id': 6, 'show_start_time': '2035-04-15T20:00:00.000Z' }
    ] )
    # ### end Alembic commands ###
    op.execute('alter sequence "Show_id_seq" restart with 5')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
